
create table projects (
    id varchar(16) NOT NULL PRIMARY KEY,
    name varchar(1024),
    description varchar(512),
    active smallint
);

create table myrecords
(
     id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    starttime timestamp NOT NULL,
    duration int NOT NULL,
    projectid varchar(16) NOT NULL,
    annotation varchar(1024),
    PRIMARY KEY(id), 
    FOREIGN KEY(projectid) REFERENCES projects(id)
);



